create table if not exists TEAM_INFO (
	TEAM_CODE INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_NAME VARCHAR(100) UNIQUE NOT NULL,
    TEAM_DETAIL VARCHAR(500),
    USE_YN CHAR(2) CHECK(USE_YN IN ('Y','N')) DEFAULT 'Y' NOT NULL
)ENGINE = INNODB;

create table if not exists MEMBER_INFO (
	MEMBER_CODE INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_NAME VARCHAR(70) NOT NULL,
    BIRTH_DATE DATE,
    DIVISION_CODE CHAR(2),
    DETAIL_INFO VARCHAR(500),
    CONTACT VARCHAR(50) NOT NULL,
    TEAM_CODE INT NOT NULL,
    ACTIVE_STATUS CHAR(2) CHECK(ACTIVE_STATUS IN ('Y','N','H')) DEFAULT 'Y' NOT NULL,
    FOREIGN KEY(TEAM_CODE) REFERENCES TEAM_INFO(TEAM_CODE) 
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE = INNODB;

INSERT INTO TEAM_INFO (TEAM_NAME,TEAM_DETAIL,USE_YN) 
VALUES 
('음악감상부','클래식 및 재즈 음악을 감상하는 사람들의 모임','Y'),
('맛집탐방부','맛집을 찾아다니는 사람들의 모임','N'),
('행복찾기부',NULL,'Y');

SELECT * FROM TEAM_INFO;
SELECT * FROM MEMBER_INFO;
INSERT INTO MEMBER_INFO 
VALUES
	(NULL,'송가인','1990-01-30',1,'안녕하세요 송가인입니다~',010-9494-9494,1,'H'),
   	(NULL,'임영웅','1992-05-03',NULL,'국민아들 임영웅입니다~',hero@trot.com,1,'Y'),
   	(NULL,'태진아',NULL,NULL,NULL,'(1급기밀)',3,'Y');