SELECT
	D.DEPT_TITLE AS '부서명',
    COUNT(E.DEPT_CODE) AS '인원',
    SUM(SALARY) AS '급여합계',
    AVG(SALARY) AS '급여평균'
FROM
	employee E
JOIN
	department D on E.DEPT_CODE = D.DEPT_ID
WHERE
	E.ENT_YN = 'N'
GROUP BY 
    D.DEPT_TITLE
WITH ROLLUP;

-- 다음

SELECT
	COUNT(*)
FROM
	employee
where
	MANAGER_ID is not null;
    
-- 다음

SELECT
	COUNT(E.EMP_ID)
FROM
	employee E
INNER JOIN
	employee M ON E.MANAGER_ID = M.EMP_ID;
    
-- 다음

SELECT
	E.EMP_NAME,
    D.EMP_NAME
FROM employee E
LEFT JOIN employee D on E.MANAGER_ID = D.EMP_ID
ORDER BY E.EMP_NAME;

-- 다음

SELECT
	E.EMP_NAME,
    D.DEPT_TITLE,
    E2.EMP_NAME,
    D2.DEPT_TITLE
FROM employee E
JOIN employee E2 on E.MANAGER_ID = E2.EMP_ID
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN department D2 ON E2.DEPT_CODE = D2.DEPT_ID
ORDER BY E.EMP_NAME;

-- 다음

SELECT
	MAX(SAL_SUM)
FROM (SELECT
			SUM(SALARY) AS SAL_SUM
		FROM employee
		group by DEPT_CODE) AS DEPT_SUM;
        
-- 다음

SELECT
	EMP_ID,
    EMP_NAME,
    DEPT_CODE,
    SALARY
FROM employee
WHERE DEPT_CODE IN (
	SELECT DEPT_ID
    FROM department
    WHERE DEPT_TITLE LIKE '%영업%')
ORDER BY DEPT_CODE;

-- 다음

SELECT
	E.EMP_ID,
    E.EMP_NAME,
    D.DEPT_TITLE,
    E.SALARY
FROM employee E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
WHERE DEPT_CODE IN (
	SELECT DEPT_ID
    FROM department
    WHERE DEPT_TITLE LIKE '%영업%')
ORDER BY D.DEPT_TITLE;
	
-- 다음
SELECT
	D.DEPT_ID,
    D.DEPT_TITLE,
    L.LOCAL_NAME,
    N.NATIONAL_NAME
FROM
	department D
JOIN location L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN nation N ON L.NATIONAL_CODE = N.NATIONAL_CODE
order by N.NATIONAL_NAME desc;
        
-- 다음
SELECT
	E.EMP_ID,
    E.EMP_NAME,
    E.SALARY,
    LN.DEPT_TITLE,
    LN.NATIONAL_NAME
FROM employee E 
JOIN (SELECT
			D.DEPT_ID,
			D.DEPT_TITLE,
			L.LOCAL_NAME,
			N.NATIONAL_NAME
		FROM
			department D
		JOIN location L ON D.LOCATION_ID = L.LOCAL_CODE
		JOIN nation N ON L.NATIONAL_CODE = N.NATIONAL_CODE
) AS LN ON E.DEPT_CODE = LN.DEPT_ID
ORDER BY LN.NATIONAL_NAME desc, LN.DEPT_TITLE;

-- 다음
SELECT
	E.EMP_ID,
    E.EMP_NAME,
    E.SALARY,
    DEPT_TITLE,
    NATIONAL_NAME,
    E.SALARY + S.MIN_SAL AS '위로금'
FROM employee E
JOIN sal_grade S ON E.SAL_LEVEL = S.SAL_LEVEL
JOIN (
	SELECT
		D.DEPT_ID,
		D.DEPT_TITLE,
		L.LOCAL_NAME,
		N.NATIONAL_NAME
	FROM
		department D
	JOIN location L ON D.LOCATION_ID = L.LOCAL_CODE
	JOIN nation N ON L.NATIONAL_CODE = N.NATIONAL_CODE
) LN ON E.DEPT_CODE = LN.DEPT_ID
WHERE LN.NATIONAL_NAME LIKE '러시아';

-- 다음

SELECT
	COUNT(*)
FROM (
SELECT
	E.EMP_ID
FROM employee E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN job J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '대리' AND D.DEPT_TITLE = '기술지원부'

UNION ALL

SELECT
	E.EMP_ID
FROM employee E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN job J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '사원' AND D.DEPT_TITLE = '인사관리부'

 UNION ALL
 
SELECT
	E.EMP_ID
FROM employee E
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
JOIN job J ON E.JOB_CODE = J.JOB_CODE
WHERE J.JOB_NAME = '부장' AND D.DEPT_TITLE LIKE '%영업%') AS TEAM;

-- 다음

SELECT
	EMP_NAME,
    SALARY,
    COUNT(*)
FROM(
SELECT
	E.EMP_ID,
	E.EMP_NAME,
    E.SALARY
FROM
	employee E
JOIN job J ON E.JOB_CODE = J.JOB_CODE
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
WHERE D.DEPT_TITLE NOT LIKE '%영업%'
AND J.JOB_NAME IN ('대리','차장')

UNION ALL

SELECT
	E.EMP_ID,
	E.EMP_NAME,
    E.SALARY
FROM
	employee E
JOIN job J ON E.JOB_CODE = J.JOB_CODE
JOIN department D ON E.DEPT_CODE = D.DEPT_ID
WHERE E.SALARY between 2000000 AND 3000000
) AS F
GROUP BY EMP_ID, EMP_NAME, SALARY
ORDER BY COUNT(*) desc, SALARY desc
LIMIT 3;

-- 다음

SELECT EMP_NAME, CONCAT(SUBSTRING(PHONE, 1, 3), '-',SUBSTRING(PHONE, 4, 4), '-', SUBSTRING(PHONE, 8, 4)) AS PHONE
FROM employee
WHERE PHONE LIKE '010%';

-- 다음

SELECT
	EMP_NAME '직원명',
    HIRE_DATE '입사일',
    FORMAT(SALARY, 'NO')'급여'
FROM employee
WHERE HIRE_DATE <= SUBDATE(CURDATE(), INTERVAL 20 YEAR)
ORDER BY HIRE_DATE, '급여';